=== kozmajani/SVOXGH_XMLGyak/SVOXGH_1005/KJ_ertoxsd.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="qualified">
    <xs:element name="feladat">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="A">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Ab">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Abx" type="xs:string"/>
                                        <xs:element name="Aby" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Ac">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Acd" type="xs:string"/>
                                        <xs:element name="Ace" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="Aa" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="A_B">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="A_Bc"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="B">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Bb">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Bbx" type="xs:string"/>
                                        <xs:element name="Bby" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="Ba" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="C">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Cb" type="xs:string"/>
                        </xs:sequence>
                        <xs:attribute name="Ca" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>

        </xs:complexType>
    </xs:element>
</xs:schema>

=== kozmajani/SVOXGH_XMLGyak/SVOXGH_1005/KJ_xsdtoxml.xml
<?xml version="1.0" encoding="UTF-8" ?>

<feladat xsi:noNamespaceSchemaLocation="KJ_ertoxsd.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <A Aa="a01">
        <Ab>
            <Abx></Abx>
            <Aby></Aby>
        </Ab>
        <Ac>
            <Acd></Acd>
            <Ace></Ace>
        </Ac>
    </A>
    <A_B>
        <A_Bc></A_Bc>
    </A_B>
    <B Ba="a02">
        <Bb>
            <Bbx></Bbx>
            <Bby></Bby>
        </Bb>
    </B>
    <C Ca="a03">
        <Cb></Cb>
    </C>
</feladat>
