=== kozmajani/SVOXGH_XMLGyak/SVOXGH_1005/KJ_konyv.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:tns="http://www.example.org/KJ_konyv" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/KJ_konyv" elementFormDefault="qualified">
	
	<xs:element name="konyvek">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="konyv" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="cim" type="xs:string" />
							<xs:element name="ev" type="xs:unsignedShort" />
							<xs:element name="kiado" type="xs:string" />
							<xs:element name="szerzo" type="xs:string" maxOccurs="unbounded" />
							<xs:element name="absztrakt" type="xs:string" />
						</xs:sequence>
						<xs:attribute name="id" type="xs:string" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== kozmajani/SVOXGH_XMLGyak/SVOXGH_1005/KJ_konyv.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE konyvek SYSTEM "KJ_konyv.dtd">

<konyvek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="KJ_konyv.xsd">


<!--<konyvek>-->
	<konyv id="id01">
		<cim>Informatikarol szolo konyv 1</cim>
		<ev>2014</ev>
		<kiado>&lt;ASD&gt; Konyvshop</kiado>
		<szerzo>Lakatos Arnold Botond</szerzo>
	</konyv>
	
	<konyv id="id02">
		<cim>Info konyv 2</cim>
		<ev>2020</ev>
		<kiado>Konyves könyvek</kiado>
		<szerzo>Bob Bobby</szerzo>
		<szerzo>Tommy Vercetti</szerzo>
	</konyv>
	
	<konyv id="id03">
		<cim>Inforol okosba 3</cim>
		<ev>2008</ev>
		<kiado>Libri kiadó</kiado>
		<szerzo>Kiss Tibor</szerzo>
		<absztrakt>Leiras..</absztrakt>
	</konyv>

</konyvek>
